name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow when a tag starting with 'v' is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t my-app:${{ github.ref }} .

    - name: Push Docker Image to Docker Hub
      run: |
        docker push my-app:${{ github.ref }}

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          cd my-app
          docker-compose pull  # Pull the latest image
          docker-compose up -d  # Deploy the app

    - name: Validate Deployment
      run: |
        curl http://${{ secrets.EC2_PUBLIC_IP }}:5000/status  # Replace with the actual EC2 IP or use a secret for dynamic fetching
