on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow on tags that start with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        # Extract the tag name (removes 'refs/tags/' from github.ref)
        TAG_NAME=${{ github.ref }}
        TAG_NAME=${TAG_NAME/refs\/tags\//}  # Strip off 'refs/tags/' prefix
        echo "Building Docker image with tag: $TAG_NAME"
        docker build -t alekyagandem/my-app:$TAG_NAME .

    - name: Push Docker Image to Docker Hub
      run: |
        # Extract the tag name again (removes 'refs/tags/' from github.ref)
        TAG_NAME=${{ github.ref }}
        TAG_NAME=${TAG_NAME/refs\/tags\//}  # Strip off 'refs/tags/' prefix
        echo "Pushing Docker image with tag: $TAG_NAME"
        docker push alekyagandem/my-app:$TAG_NAME

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          cd my-app
          docker-compose pull
          docker-compose up -d

    - name: Validate Deployment
      run: |
        curl http://${{ secrets.EC2_PUBLIC_IP }}:5000/status
