name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow when a tag starting with 'v' is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build Docker Image
      run: |
        # Extract the tag from the GitHub reference and remove 'refs/tags/'
        TAG_NAME=${GITHUB_REF#refs/tags/}
        docker build -t alekyagandem/my-app:$TAG_NAME .

    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        # Extract the tag from the GitHub reference and remove 'refs/tags/'
        TAG_NAME=${GITHUB_REF#refs/tags/}
        docker push alekyagandem/my-app:$TAG_NAME

    # Step 6: SSH into EC2 and Deploy the Docker container
    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          # Navigate to the application directory
          cd /path/to/your/application/directory

         
