on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        TAG_NAME=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
        docker build -t alekyagandem/my-app:$TAG_NAME .

    - name: Push Docker Image to Docker Hub
      run: |
        TAG_NAME=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
        docker push alekyagandem/my-app:$TAG_NAME

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          cd my-app
          docker-compose pull
          docker-compose up -d

    - name: Validate Deployment
      run: |
        curl http://${{ secrets.EC2_PUBLIC_IP }}:5000/status
